function [ ] = prae_showInstructions(window,imageLocs,colors,keys,fMRI,prac)
% instructions, cue conditioning procedure, and practice trials

%% stimuli and response keys
cueCond = prac.cueCond;
pracTrials = prac.pracTrials;

switch fMRI
    case 0
        respKeys = {'6 key'; '7 key'; '8 key'};
    case 1
        respKeys = {'INDEX finger button'; 'MIDDLE finger button'; 'RING finger button'};
end

 %% instructions
 msg = sprintf([...
     'Welcome!\n\n' ...
     'Before starting this activity we will review the instructions.\n\n' ...
     'Press any button to start.']);
 prae_drawMessage(window,msg);
 Screen('Flip',window);
 FlushEvents('keyDown');
 WaitSecs(1);
 KbWait(-1);
 
 msg = sprintf([...
     'In this activity you will be viewing different types of pictures.\n\n' ...
     'Some of the pictures will be pleasant, some unpleasant, and some neutral.\n\n' ...
     'Press any button to continue.']);
 prae_drawMessage(window,msg);
 Screen('Flip',window);
 FlushEvents('keyDown');
 WaitSecs(1);
 KbWait(-1);

 msg = sprintf([...
     'Each trial involves a sequence of events. Usually a cue (or symbol)\n\n' ...
     'will appear first to indicate the type of picture you will see.\n\n' ...
     'Press any button to continue.']);
 prae_drawMessage(window,msg);
 Screen('Flip',window);
 FlushEvents('keyDown');
 WaitSecs(1);
 KbWait(-1);

 msg = sprintf([...
     'A green plus sign (+) indicates that a PLEASANT picture will appear.\n\n' ...
     'A white circle (o) indicates that a NEUTRAL picture will appear.\n\n' ...
     'A red minus sign (-) indicates that an UNPLEASANT picture will appear.\n\n' ...
     'Press any button to continue.']);
 prae_drawMessage(window,msg);
 Screen('Flip',window);
 FlushEvents('keyDown');
 WaitSecs(1);
 KbWait(-1);
 
 msg = sprintf([...
     'The cue will appear for two seconds, followed by a white dot for several seconds.\n\n' ...
     'Please use this entire time to anticipate (think about) the upcoming picture.\n\n' ...
     'Press any button to continue.']);
 prae_drawMessage(window,msg);
 Screen('Flip',window);
 FlushEvents('keyDown');
 WaitSecs(1);
 KbWait(-1);

 msg = sprintf([...
     'Next, the picture will appear for two seconds, and will be followed by a white dot for several seconds.\n\n' ...
     'During this entire time, please reflect on (think about) the picture (pleasant, neutral, or unpleasant).\n\n' ...
     'Finally, you will always see the word "REST", indicating that you can simply rest in between trials.\n\n'...
     'Press any button to view some sample trials.']);
 prae_drawMessage(window,msg);
 Screen('Flip',window);
 FlushEvents('keyDown');
 WaitSecs(1);
 KbWait(-1);
 WaitSecs(1);
 
 %% Cue conditioning
 prae_prac_cueCond(window,imageLocs,colors,cueCond)
 
 %% instructions
 msg = sprintf([...
     'To review: The cue indicates what type of picture you will see (pleasant, neutral, or unpleasant).\n\n' ...
     'Use the period before the picture appears to anticipate (think about) the type of picture you will see.\n\n' ...
     'Once the picture appears, please reflect on (think about) the picture (pleasant, neutral, or unpleasant).\n\n' ...
     'When you see the word "REST" this indicatest that the trial is over an another will begin shortly.\n\n' ...
     'Press any button to continue.']);
 prae_drawMessage(window,msg);
 Screen('Flip',window);
 FlushEvents('keyDown');
 WaitSecs(1);
 KbWait(-1);

 msg = sprintf([...
     'On a small number of trials, at the end of the trial you will be asked to rate whether\n\n' ...
     'the picture was pleasant, neutral, or unpleasant. Please use the buttons to provide your rating.\n\n'...
     'Press the %s to rate the picture as positive.\n\n'...
     'Press the %s to rate the picture as neutral.\n\n'...
     'Press the %s to rate the picture as negative.\n\n'...
     'You will only be asked to rate the pictures on a few trials.\n\n'...
     'Press any button to continue.'],respKeys{1},respKeys{2},respKeys{3});
 prae_drawMessage(window,msg);
 Screen('Flip',window);
 FlushEvents('keyDown');
 WaitSecs(1);
 KbWait(-1);

 msg = sprintf([...
     'Finally, some trials will leave out some parts of the sequence. For example, on some trials\n\n'...
     'you will see a cue, followed by a white dot, but the picture will not appear. On other trials\n\n' ...
     'you will not see a cue followed by a white dot; instead, the picture will appear right away.\n\n'...
     'Please do not be alarmed by this, it is a part of the activity. Regardless of these differences\n\n' ...
     'your job will always be to anticipate the picture duirng the cue followed by a white dot\n\n' ...
     'and to reflect on the picture during the picture followed by a white dot. \n\n'...
     'Press any button to continue.']);
 prae_drawMessage(window,msg);
 Screen('Flip',window);
 FlushEvents('keyDown');
 WaitSecs(1);
 KbWait(-1);

 switch fMRI
     case 0
         msg = sprintf([...
             'It will help to see examples of each trial type. In a moment we will present some practice trials.\n\n' ...
             'Do your best to anticipate and to reflect on the type of picture during the appropriate periods.\n\n'...
             'Remember that some trials will have missing parts and some will ask you to rate the picutre using the buttons.\n\n'...
             'If you have any questions, please alert your experimenter.\n\n'...
             'Otherwise, press any button to practice.']);
         prae_drawMessage(window,msg);
         Screen('Flip',window);
         FlushEvents('keyDown');
         WaitSecs(1);
         KbWait(-1);
         Screen('Flip', window);
         WaitSecs(1);
     case 1       
         msg = sprintf([...
             'It will help to see examples of each trial type. In a moment we will present some practice trials.\n\n' ...
             'Do your best to anticipate and to reflect on the type of picture during the appropriate periods.\n\n'...
             'Remember that some trials will have missing parts and some will ask you to rate the picutre using the buttons.\n\n'...
             'If you have any questions, please squeeze the squeeze ball to alert your experimenter.\n\n'...
             'Otherwise, press any button to practice.']);
         prae_drawMessage(window,msg);
         Screen('Flip',window);
         FlushEvents('keyDown');
         WaitSecs(1);
         KbWait(-1);
         Screen('Flip', window);
         WaitSecs(1);
 end % switch
 
 %% practice trials
 prae_prac_pracTrials(window,imageLocs,colors,keys,pracTrials);
 
 %% instructions
 
 msg = sprintf([...
     'Great job! To review: Use the cue followed by a white dot to anticipate the type of picture you will see.\n\n'...
     'Once the picture appears please reflect on the picture (pleasant, neutral, or unpleasant).\n\n'...
     'Some trials will ask you to rate the picture using the buttons. Some trials will leave out parts of the sequence.\n\n'...
     'Press any button to continue.']);
 prae_drawMessage(window,msg);
 Screen('Flip',window);
 FlushEvents('keyDown');
 WaitSecs(1);
 KbWait(-1);
 
 msg = sprintf([...
     'You do not need to try and guess what will happen on each trial. Your job is to simply to\n\n'...
     'anticipate the picture during the cue followed by a white dot, and to reflect on the picture\n\n'...
     'during the picture followed by a white dot. The word "rest" will always appear in between the trials.\n\n'...
     'Press any button to continue.']);
 prae_drawMessage(window,msg);
 Screen('Flip',window);
 FlushEvents('keyDown');
 WaitSecs(1);
 KbWait(-1);
 
 switch fMRI
     case 0
         msg = sprintf([...
             'When you get into the scanner you will perform this task several times.\n\n'...
             'If you have any questions about this activity please discuss them with\n\n' ...
             'your experimenter now. There are no silly questions, we want you to go\n\n' ...
             'into the scanner feeling sure about these instructions.\n\n' ...
             'Please contact your experimenter now to continue.']);
         prae_drawMessage(window,msg);
         Screen('Flip',window);
         FlushEvents('keyDown');
         WaitSecs(1);
         
     case 1
         msg = sprintf([...
             'If you have any questions about this activity please ask your experimenter now, by squeezing\n\n' ...
             'the squeeze ball to get his/her attention. If you are ready to continue, press any button.']);
         prae_drawMessage(window,msg);
         Screen('Flip',window);
         FlushEvents('keyDown');
         WaitSecs(1);
         KbWait(-1);
         
         msg = sprintf([...
             'We will be begin in just a moment. Do your best to pay attention to every trial.\n\n' ...
             'Remember to remain as still as possible throughout the activity so that we can\n\n'...
             'get the best images of your brain and brain signals. Press any button to continue.']);
         prae_drawMessage(window,msg);
         Screen('Flip',window);
         FlushEvents('keyDown');
         WaitSecs(1);
         KbWait(-1);
         
 end % swtich 
 
end % main function

